### PR TITLE
Fixed scraping from MoHFW website

### PR DESCRIPTION
**Pull request by dhirenmathur**
Hi - I came across this issue as you have tagged it under Hacktoberfest and have attempted to fix it to best of my ability - 

Solution for #7 #8  #9  - 
On looking at the XML that was being returned I found that the table body was not being captured, this was due to the behaviour of webpage where we need to click on the "Click to expand" link in order to view the table. I enabled javascript in the webclient and added that functionality to click and then fetch page from the controller.  

Also created/updated the response model as the MoHFW website displays active cases for state and not total confirmed cases for state. 

While this immediately fixes the issues you mentioned above, it introduces performance issues that might need to be optimised - 

1) The webclient waits 2s for the javascript to load in the background adding latency
2) If javascript load fails - it gives IndexOutOfBoundsError

One possible solution is to introduce a cache with a 24 hour TTL as the website refreshes data everyday. 

image
image
image

### CODE REVIEW

**Comment by dhirenmathur** [comment]
Maybe you could help me with why the CI step failed, the `mvn clean install` step passes in my local machine and application comes up and runs successfully 
image

**Comment by Muhib007dev** [comment]
Thank you so much for fixing this issue I didn't thought about that. Also I am just not used to git that much can you please elaborate how can I help you out. Or should I directly go and click on merge.

**Comment by dhirenmathur** [comment]
You have added these Github actions that show as failed, but on looking at your previous PRs looks like none of the PRs have satisfied the checks, You probably need to recheck the configuration of github actions. 

Apart from that, generally how a git workflow works is:
Maintainer (you) or anyone else opens an issue in the repo. 
Contributor (me) will assess the problem and propose a fix (Pull request) 
Then maintainer will review the code and merge the pull request. 
Close the issue as resolved. 


Reason behind saying this is you should not blindly merge any code into your repository, you should review the code that is submitted and approve it first before merging

**Comment by Muhib007dev** [comment]
Oh ok I got it, it is actually because I was using netlify to deploy this app but it didn't worked out so I used heroku then, but I forgot to remove netlify that is why it showing these failed checks, although I will check everything now and will merge it. Thank you for your guidance.

**Comment by dhirenmathur** [comment]
Sounds good 👍🏻 Let me know if I need to change anything in the code. And do consider my suggestion from the first comment to add a cache, it will help in performance.

**Comment by Muhib007dev** [comment]
Yeah sure, I will do that definitely I haven't tried doing caching in spring boot it will be interesting to learn and implement it in this project. Thank you so much. I learned so much from you. Keep contributing.

**Pull request merged**
